version: "3.8"
services:
  devcontainer:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
    user: vscode
    command: sleep infinity
